/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/fields/Button.vue')['default']
    ButtonInput: typeof import('./src/components/inputs/ButtonInput.vue')['default']
    CanvasComponent: typeof import('./src/components/CanvasComponent.vue')['default']
    CheckboxField: typeof import('./src/components/fields/CheckboxField.vue')['default']
    CheckboxInput: typeof import('./src/components/inputs/CheckboxInput.vue')['default']
    DateField: typeof import('./src/components/fields/DateField.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    FieldItem: typeof import('./src/components/FieldItem.vue')['default']
    FieldOptionsPanel: typeof import('./src/components/fields/FieldOptionsPanel.vue')['default']
    FileField: typeof import('./src/components/fields/FileField.vue')['default']
    FormBuilder: typeof import('./src/components/FormBuilder.vue')['default']
    FormRenderer: typeof import('./src/components/FormRenderer.vue')['default']
    FormSectionItem: typeof import('./src/components/FormSectionItem.vue')['default']
    FormWrapper: typeof import('./src/components/FormWrapper.vue')['default']
    HeadingField: typeof import('./src/components/fields/HeadingField.vue')['default']
    HiddenField: typeof import('./src/components/fields/HiddenField.vue')['default']
    LanguageSelect: typeof import('./src/components/LanguageSelect.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NumberField: typeof import('./src/components/fields/NumberField.vue')['default']
    Palette: typeof import('./src/components/Palette.vue')['default']
    ParagraphField: typeof import('./src/components/fields/ParagraphField.vue')['default']
    RadioField: typeof import('./src/components/fields/RadioField.vue')['default']
    RadionGroup: typeof import('./src/components/inputs/RadionGroup.vue')['default']
    SectionField: typeof import('./src/components/fields/SectionField.vue')['default']
    SectionRenderer: typeof import('./src/components/SectionRenderer.vue')['default']
    SelectField: typeof import('./src/components/fields/SelectField.vue')['default']
    SelectInput: typeof import('./src/components/inputs/SelectInput.vue')['default']
    TextAreaField: typeof import('./src/components/fields/TextAreaField.vue')['default']
    TextareaInput: typeof import('./src/components/inputs/TextareaInput.vue')['default']
    TextField: typeof import('./src/components/fields/TextField.vue')['default']
    TextInput: typeof import('./src/components/inputs/TextInput.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
  }
}
