/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/fields/Button.vue')['default']
    Canvas: typeof import('./src/components/Canvas.vue')['default']
    CanvasComponent: typeof import('./src/components/CanvasComponent.vue')['default']
    CheckboxField: typeof import('./src/components/fields/CheckboxField.vue')['default']
    DateField: typeof import('./src/components/fields/DateField.vue')['default']
    FieldItem: typeof import('./src/components/FieldItem.vue')['default']
    FieldOptionalPanel: typeof import('./src/components/fields/FieldOptionalPanel.vue')['default']
    FieldOptionsPanel: typeof import('./src/components/fields/FieldOptionsPanel.vue')['default']
    FileField: typeof import('./src/components/fields/FileField.vue')['default']
    FormBuilder: typeof import('./src/components/FormBuilder.vue')['default']
    FormSectionItem: typeof import('./src/components/FormSectionItem.vue')['default']
    FormTest: typeof import('./src/components/FormTest.vue')['default']
    HeadingField: typeof import('./src/components/fields/HeadingField.vue')['default']
    HiddenField: typeof import('./src/components/fields/HiddenField.vue')['default']
    LanguageSelect: typeof import('./src/components/LanguageSelect.vue')['default']
    NumberField: typeof import('./src/components/fields/NumberField.vue')['default']
    Palette: typeof import('./src/components/Palette.vue')['default']
    ParagraphField: typeof import('./src/components/fields/ParagraphField.vue')['default']
    RadioField: typeof import('./src/components/fields/RadioField.vue')['default']
    SectionField: typeof import('./src/components/fields/SectionField.vue')['default']
    SelectField: typeof import('./src/components/fields/SelectField.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    TextAreaField: typeof import('./src/components/fields/TextAreaField.vue')['default']
    TextField: typeof import('./src/components/fields/TextField.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
