<script setup lang="ts">
import { ref, watch } from 'vue'
import type { FormSection } from '@/types/fields'
import SectionRenderer from '@/components/SectionRenderer.vue'

// Props: schema generated by FormBuilder
const props = defineProps<{
  sections: FormSection[]
}>()

// Reactive form data keyed by field.id
const formData = ref<Record<string, any>>({})

// Initialize formData with default values
props.sections.forEach(section => {
  section.fields.forEach(field => {
    formData.value[field.id] = field.value ?? ''
  })
})

// Emit form data upwards if needed
const emit = defineEmits<{ (e: 'update', value: Record<string, any>): void }>()

watch(
  () => formData.value,
  val => emit('update', val),
  { deep: true }
)
</script>

<template>
  <div style="width: 75%; margin: auto" class="space-y-6 w-96 mx-auto ub-vue-form-builder">
    <SectionRenderer v-for="section in props.sections" :key="section.id" :section="section" v-model="formData" />
  </div>
</template>
