<script setup lang="ts">
import { ref, watch } from 'vue'
import type { FormSection, FormField } from '@/types/fields'

// Props: schema generated by FormBuilder
const props = defineProps<{
  sections: FormSection[]
}>()

// Reactive form data keyed by field.id
const formData = ref<Record<string, any>>({})

// Initialize formData with default values
props.sections.forEach(section => {
  section.fields.forEach(field => {
    formData.value[field.id] = field.value ?? ''
  })
})

// Emit form data upwards if needed
const emit = defineEmits<{ (e: 'update', value: Record<string, any>): void }>()

watch(
  () => formData.value,
  val => emit('update', val),
  { deep: true }
)

// Small helper: map field type to component
const getComponent = (field: FormField) => {
  switch (field.type) {
    case 'text':
    case 'number':
      return 'n-input'
    case 'textarea':
      return 'n-input'
    case 'select':
      return 'n-select'
    case 'checkbox':
      return 'n-checkbox'
    case 'radio':
      return 'n-radio-group'
    case 'hidden':
      return 'input'
    default:
      return 'n-input'
  }
}
</script>

<template>
  <div class="space-y-6">
    <div
      v-for="section in props.sections"
      :key="section.id"
      class="border rounded p-4 shadow-sm bg-white dark:bg-gray-900"
    >
      <h2 v-if="section.title" class="text-lg font-semibold mb-4">
        {{ section.title }}
      </h2>

      <!-- Render fields -->
      <div v-for="field in section.fields" :key="field.id" class="mb-4">
        <label
          v-if="field.label && field.type !== 'checkbox' && field.type !== 'radio'"
          class="block mb-1 text-sm font-medium text-gray-700 dark:text-gray-300"
        >
          {{ field.label }}
          <span v-if="field.required" class="text-red-500">*</span>
        </label>

        <!-- Dynamic Rendering -->
        <component :is="getComponent(field)" v-model:value="formData[field.id]" v-bind="getProps(field)">
          <!-- Checkbox / Radio Labels -->
          <template v-if="field.type === 'checkbox'">
            {{ field.label }}
          </template>
          <template v-if="field.type === 'radio'">
            <n-radio v-for="opt in field.options || []" :key="opt.value" :value="opt.value">
              {{ opt.label }}
            </n-radio>
          </template>
        </component>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
// Helper to pass props per field type
function getProps(field: FormField) {
  switch (field.type) {
    case 'text':
    case 'number':
    case 'textarea':
      return {
        type: field.subType || field.type,
        placeholder: field.placeholder,
        required: field.required,
        minlength: field.min,
        maxlength: field.max,
        step: field.step,
        autosize: field.type === 'textarea',
      }
    case 'select':
      return {
        options: field.options || [],
        placeholder: field.placeholder,
        multiple: field.multiple || false,
      }
    case 'checkbox':
      return {
        value: field.value ?? false,
      }
    case 'radio':
      return {}
    case 'hidden':
      return {
        type: 'hidden',
      }
    default:
      return {}
  }
}
</script>
